alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK6wgxxgelastu3blt5vd883rdo
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK6wgxxgelastu3blt5vd883rdo
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FKpbccg5sg1y87p6rnn13mtuol4
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Class_Student drop constraint FKhcxqus7alhtujwkt9vrskl96u
alter table Class_Student drop constraint FKiyrdd7o3adlxvqvasphgo0jsh
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Class_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKsnmaujl2vs53b5t1n1lne7bs0
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKsnmaujl2vs53b5t1n1lne7bs0
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKsnmaujl2vs53b5t1n1lne7bs0
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKsnmaujl2vs53b5t1n1lne7bs0
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKsnmaujl2vs53b5t1n1lne7bs0
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKsnmaujl2vs53b5t1n1lne7bs0
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKperuy6cbxmoirf0u315wix6pp
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKsnmaujl2vs53b5t1n1lne7bs0
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phone cascade
drop table if exists Student cascade
